### ISSUE TITLE
Don't require tabaqa.json in local .vscode directory

### ISSUE THREAD

**Issue by carlosaya** [kalimahapps/tabaqa#1]
Hi, just installed this and it works, but only if I create a `./.vscode/tabaqa.json` in every project inside the root directory.  Is this the intent, or a bug?  In my opinion this is unnecessary overhead.  It seems that the extension should have an option to always search up the tree without having to create this file each time.

**Comment by abdul-alhasany** [comment]
Hi @carlosaya 
You don't need to create a new `tabaqa.json` file in each directory. You just need to create it in the directory that you open in vscode.

If you provide a public repo I might be able to look into and fix any possible issues.

**Comment by carlosaya** [comment]
Hi @abdul-alhasany.  That's what I am saying.  I don't want to have to create this file in every project directory.  

I have a directory like this...

```
Client1/
     Project1/
     Project2/
     Project3/
``` 

If I have `Client1/.vscode/tabaqa.json` then I want it to be automatically inherited in each project under the Client1 directory without having to create `.vscode/tabaqa.json` in every project.

Hope that makes sense.  Maybe when declaring the root tabaqa.json we can use a property like `forceInheritance: true|false` to toggle this feature?

**Comment by carlosaya** [comment]
I just opened a PR for this:  https://github.com/kalimahapps/tabaqa/pull/2

Forgive me for using a global, I am not much of a TS developer and couldn't think of another way to get this done.  I tested it and it works as expected.  I have not bothered with updating the tests or docs for this yet.  If you are happy to add this feature then I can spend some time to add tests around it and update the readme in my PR.

**Comment by abdul-alhasany** [comment]
thanks for the PR. I am currently overseas. I will try to look into it once I am back.

**Comment by carlosaya** [comment]
No worries. Safe travels!

**Comment by abdul-alhasany** [comment]
I was thinking about how approach for a while. I think adding extra property might confuse users since espcially when used with `root:true`.
I think the better approach is to display an alert to the use stating that there is a `tabaqa.json` file in the parent folders and ask if the user would like to apply it. This combined with an extension setting so the user does not have to do it (if set) to check the message every time they open VSCode.

**Comment by abdul-alhasany** [comment]
This is added now in latest version. I will add the settings option later when possible
