### ISSUE TITLE
Support for `.code-workspace` file inheritence?

### ISSUE THREAD

**Issue by Makeshift** [kalimahapps/tabaqa#3]
This is a lovely little plugin and I find it quite handy in keeping my settings organised. 

I've recently found myself designing a monorepo layout and I've provided a `default.vscode.code-workspace` in the top level, which can be copied and modified to the other developers liking. With tabaqa, we can have a main 'settings' file that we inherit and extend, but the list of workspaces stored in the `code-workspace` won't be inherited into the other devs copies.

Have you considered adding support to tabaqa to allow `code-workspace` files to be extended in a similar way?

**Comment by abdul-alhasany** [comment]
It seems a good idea. It might take me some time to implement it and test it. Meanwhile you can set the `extends` property to the path of the default folder.
